apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: intellipaat-cluster
  region: us-east-1

managedNodeGroups:
  - name: eks-worker-nodes
    minSize: 2
    maxSize: 5
    desiredCapacity: 2
    instanceType: t3.small
    ssh:
      allow: true
      publicKeyPath: ~/.ssh/aws.pub
    iam:
      withAddonPolicies:
        externalDNS: true
        autoScaler: true
        ebs: true
        efs: true
        cloudWatch: true
        albIngress: true
