apiVersion: v1
kind: Service
metadata:  
  name: nginx-nodeport-service
spec:
  selector:    
    app: nginx-deploy
  type: NodePort
  ports:  
  - name: http
    port: 8080
    targetPort: 80
    nodePort: 31000
    protocol: TCP
