apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-cont
        image: nginx:1.9.1
        ports:
        - containerPort: 80
        # Readiness probe will check whether the application ready to start serving the traffic. Once the Pod is in Ready state, this healthcheck willno longer be performed.
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 20
        # Liveness probe will constantly check for the application status till the POD is terminated
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 60

